export { default as jdnftMenu } from '~/assets/jdnft/menu.png'
export { default as jdnftSeries } from '~/assets/jdnft/series.png'
export { default as jdnftSynthetic } from '~/assets/jdnft/synthetic.png'
export { default as jdnftJdDAO } from '~/assets/jdnft/jdDAO.png'
export { default as jdnftWhitepaper } from '~/assets/jdnft/whitepaper.png'

export { default as jdnftMain } from '~/assets/jdnft/main.png'
export { default as jdnftDirectionTip } from '~/assets/jdnft/directionTip.png'
export { default as jdnftBox } from '~/assets/jdnft/box.png'
export { default as jdnftAvatarBg } from '~/assets/jdnft/avatarBg.png'
export { default as openbox } from '~/assets/jdnft/openbox.jpg'
export { default as top } from '~/assets/jdnft/top.jpg'
export { default as toplong } from '~/assets/jdnft/toplong.jpg'

export { default as discord } from '~/assets/public/discord.svg'
export { default as twitter } from '~/assets/public/twitter.svg'
export { default as telegram } from '~/assets/public/telegram.svg'

export { default as jdnftBottomBg } from '~/assets/jdnft/bottomBg.jpg'
export { default as jdnftBg } from '~/assets/jdnft/bg.png'
export { default as jdnftP1 } from '~/assets/jdnft/p1.png'
