[package]
name = "todomvc"
version = "0.1.0"
edition = "2021"

[dependencies]
akun = { path = "../.." }
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2"

[dependencies.web-sys]
version = "0.3"
features = ["HtmlInputElement", "KeyboardEvent"]
